# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Jx < Formula
  desc "Easily install, upgrade, and run JVM applications"
  homepage "https://github.com/c-fraser/jx"
  version "0.2.3"
  license "Apache-2.0"

  depends_on "openjdk" => :optional

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/c-fraser/jx/releases/download/v0.2.3/jx_0.2.3_Darwin_arm64.tar.gz"
      sha256 "30a4285fe65d53020b786b8149c5ffe5076a26e0d10f3d3e3a859c5c86276e8b"

      def install
        bin.install "jx"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/c-fraser/jx/releases/download/v0.2.3/jx_0.2.3_Darwin_x86_64.tar.gz"
      sha256 "56129de66e6643db2fb06a7c17997d1536d5fd2ba349e32814674ea12cbb4c42"

      def install
        bin.install "jx"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/c-fraser/jx/releases/download/v0.2.3/jx_0.2.3_Linux_arm64.tar.gz"
      sha256 "789b64930bca92bfdc8d77473b5deeb8b7453bad6147d627539206fe3915437b"

      def install
        bin.install "jx"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/c-fraser/jx/releases/download/v0.2.3/jx_0.2.3_Linux_x86_64.tar.gz"
      sha256 "cc9ea2449de4dfaf35c5a4012550736f12b11622c029ec8890e991ad8f808f1e"

      def install
        bin.install "jx"
      end
    end
  end

  test do
    system "#{bin}/jx -v"
  end
end
