# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Jx < Formula
  desc "Easily install, upgrade, and run JVM applications"
  homepage "https://github.com/c-fraser/jx"
  version "0.2.5"
  license "Apache-2.0"

  depends_on "openjdk" => :optional

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/c-fraser/jx/releases/download/v0.2.5/jx_0.2.5_Darwin_arm64.tar.gz"
      sha256 "16821b23df93ff41424c52a404b601841b48a48317b06bd584b7a6c16a985fc0"

      def install
        bin.install "jx"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/c-fraser/jx/releases/download/v0.2.5/jx_0.2.5_Darwin_x86_64.tar.gz"
      sha256 "4aa6c47995ffa06b0c92871ac1df9635137b36b571ddd4fb805fbbca43c02ae0"

      def install
        bin.install "jx"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/c-fraser/jx/releases/download/v0.2.5/jx_0.2.5_Linux_arm64.tar.gz"
      sha256 "b0392abbc29a3c2973ae80a8c13a135da1a1550115572119735200eeab097a96"

      def install
        bin.install "jx"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/c-fraser/jx/releases/download/v0.2.5/jx_0.2.5_Linux_x86_64.tar.gz"
      sha256 "e91d91c53ada1c1bb0ff43035d3755cc8109c230547677fae63c51fbdba7f520"

      def install
        bin.install "jx"
      end
    end
  end

  test do
    system "#{bin}/jx -v"
  end
end
